spring:
  config:
    activate:
      on-profile: dev
  application:
    name: My Store
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    baseline-description: "init"
    baseline-version: 0

server:
  servlet:
    context-path: /api

cors:
    allowed-origins: ${ALLOWED_ORIGIN}
    allowed-methods: "*"
    allowed-headers: "*"